service: til

plugins:
  - serverless-webpack
  
provider:
  name: aws
  stage: prod
  runtime: nodejs14.x
  region: ap-southeast-2
  deploymentBucket:
    name: til-serverless-deployments
  logRetentionInDays: 30
  environment:
    ENV: ${file(stage-prod.yml):ENV}
    MYSQL_HOST: ${file(stage-prod.yml):MYSQL_HOST}
    MYSQL_USER: ${file(stage-prod.yml):MYSQL_USER}
    MYSQL_PASSWORD: ${file(stage-prod.yml):MYSQL_PASSWORD}
    MYSQL_DATABASE: ${file(stage-prod.yml):MYSQL_DATABASE}
    WEB_URL: ${file(stage-prod.yml):WEB_URL}
    COGNITO_CLIENT_ID: ${file(stage-prod.yml):COGNITO_CLIENT_ID}
    FACEBOOK_CLIENT_SECRET: ${file(stage-prod.yml):FACEBOOK_CLIENT_SECRET}
    GITHUB_CLIENT_ID: ${file(stage-prod.yml):GITHUB_CLIENT_ID}
    GITHUB_CLIENT_SECRET: ${file(stage-prod.yml):GITHUB_CLIENT_SECRET}
    LINKEDIN_CLIENT_ID: ${file(stage-prod.yml):LINKEDIN_CLIENT_ID}
    LINKEDIN_CLIENT_SECRET: ${file(stage-prod.yml):LINKEDIN_CLIENT_SECRET}
    COGNITO_CLIENT_SECRET: ${file(stage-prod.yml):COGNITO_CLIENT_SECRET}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"
    - Effect: "Allow"
      Action: rds:*
      Resource: "*"
    
functions:
  getTags:
    handler: lambda/tags/get-tags.getTags
    events:
      - http:
          path: tags
          method: get
  getTils:
    handler: lambda/tils/get-tils.getTils
    events:
      - http:
          path: tils
          method: get
  getStatistics:
    handler: lambda/statistics/get-statistics.getStatistics
    events:
      - http:
          path: statistics
          method: get
  authUserWithCognito:
    handler: lambda/auth/cognito.getUser
    events:
      - http:
          path: auth/cogAuth
          method: get          
  authUserWithLinkedin:
    handler: lambda/auth/linkedin.getUser
    events:
      - http:
          path: auth/liAuth
          method: get  
  authUserWithGithub:
    handler: lambda/auth/github.getUser
    events:
      - http:
          path: auth/ghAuth
          method: get                                      

