export enum ActionType {
    COMBINED_ACTION = 'COMBINED_ACTION',
    SET_USER = 'SET_USER',
    SET_IS_SEARCH_FORM_VISIBLE = 'SET_IS_SEARCH_FORM_VISIBLE',
    SET_IS_ABOUT_POPUP_VISIBLE = 'SET_IS_ABOUT_POPUP_VISIBLE'
} 
